// tslint:disable
/**
 * Echo Forum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CategoryInfo
 * @export
 * @interface CategoryInfo
 */
export interface CategoryInfo {
    /**
     * Semantic64<\"category\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof CategoryInfo
     */
    category_id: string;
    /**
     * The rgba hex color represent.
     * @type {string}
     * @memberof CategoryInfo
     */
    color: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryInfo
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryInfo
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryInfo
     */
    create_time: string;
    /**
     * Semantic64<\"user\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof CategoryInfo
     */
    create_user: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryInfo
     */
    update_time: string;
    /**
     * Semantic64<\"user\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof CategoryInfo
     */
    update_user: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryInfo
     */
    type: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryInfo
     */
    status: number;
}


