// tslint:disable
/**
 * Echo Forum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CategoryCreate
 * @export
 * @interface CategoryCreate
 */
export interface CategoryCreate {
    /**
     * 
     * @type {string}
     * @memberof CategoryCreate
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryCreate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryCreate
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryCreate
     */
    description?: string;
}


