// tslint:disable
/**
 * Echo Forum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CategoryEdit
 * @export
 * @interface CategoryEdit
 */
export interface CategoryEdit {
    /**
     * Semantic64<\"category\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof CategoryEdit
     */
    category_id: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryEdit
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryEdit
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryEdit
     */
    color?: string;
}


