// tslint:disable
/**
 * Echo Forum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TopicEdit
 * @export
 * @interface TopicEdit
 */
export interface TopicEdit {
    /**
     * Semantic64<\"topic\">，The 64-bit hexadecimal string identifier
     * @type {string}
     * @memberof TopicEdit
     */
    topic_id: string;
    /**
     * 
     * @type {string}
     * @memberof TopicEdit
     */
    link?: string;
    /**
     * 
     * @type {string}
     * @memberof TopicEdit
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TopicEdit
     */
    description?: string;
}


