name = "echo-forum"
main = "build/worker/shim.mjs"
compatibility_date = "2025-03-23"

[build]
command = "worker-build --dev"

[dev]
port = 8080

[env.dev.vars]
DATABASE_URL = "dev.example.com"

[env.production.vars]
DATABASE_URL = "<SECRET_URL>"
